### ISSUE TITLE
Create the JS for dark mode

### ISSUE THREAD

**Issue by KeithPetr** [KeithPetr/Group-Salesboard#10]
Add the JS to the index.js file to make the dark mode option toggle through the appropriate colors.

**Comment by codercreative** [comment]
I will try to take this one on. I haven't tried to create dark mode before -- so I may have to reach out for help.

**Comment by famanakis** [comment]
Basic functionality have been achieved in CSS and JS.  We need to look at Keith's suggestion to add more CSS changes to the page when the button toggles between dark and light.
