### ISSUE TITLE
Move eventListener code to be after the Functions section

### ISSUE THREAD

**Issue by famanakis** [KeithPetr/Group-Salesboard#5]
One code reviewer pointed out that occasionally there are errors when an eventListener is run before the function is presented in the JS file.  He said that having the eventListeners at the bottom - after the function section would prevent this (be it an uncommon but sometime rare appearance of a bug) from happening.

**Comment by codercreative** [comment]
I have placed the event listeners at the bottom of the index.js file. 

Good to know about the possible bug issue.
